import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {

  title: any;
  private testList = [
    {
      address: null,
      alias: 'Austin Taylor',
      birthDate: '01/01/0001',
      city: null,
      comment: null,
      country: null,
      department: 'Brokerage',
      departmentId: 10,
      dialpad: '11111',
      firstName: 'Austin',
      lastName: 'Taylor',
      gender: 'F',
      hireDate: null,
      id: 1,
      jobTitle: 'CEO',
      jobTitleId: 5,
      location: null,
      locationId: 0,
      manager: true,
      managerId: 0,
      personalEmail: 'jasmine.smith@taylor-corp.net',
      personalPhone: '111111',
      picture: null,
      status: true,
      userCreated: true,
      userId: 1,
      userType: 'Broker',
      userTypeId: 2,
      workEmail: 'jasmine.s@taylor-corp.net',
      zip: null,
      zipId: 0,
      isManager: true,
      employees: []
    },

    {
      address: 'admin',
      alias: 'Admin',
      birthDate: '01/01/0001',
      city: null,
      comment: null,
      country: null,
      department: 'Unassigned',
      departmentId: 1,
      dialpad: '11111',
      firstName: 'Sergei',
      lastName: 'Krndija Krndija',
      gender: null,
      hireDate: null,
      id: 2,
      jobTitle: 'Director',
      jobTitleId: 10,
      location: null,
      locationId: 0,
      manager: true,
      managerId: 1,
      personalEmail: null,
      personalPhone: '1111',
      picture: 'http://77.77.220.74:8082/Media/1221shutterstock_35662648.jpg',
      status: false,
      userCreated: true,
      userId: 209,
      userType: 'Admin',
      userTypeId: 1,
      workEmail: 'admin@taylor-corp.net',
      zip: null,
      zipId: 0,
      isManager: true,
      employees: []
    },

    {
      address: null,
      alias: 'Ally Andersen',
      birthDate: '01/01/0001',
      city: 'Sarajevo ',
      comment: null,
      country: 'Bosnia and Herzegovina',
      department: 'Brokerage',
      departmentId: 9,
      dialpad: '619-734-9766',
      firstName: 'Joseph',
      lastName: 'Lassen',
      gender: 'F',
      hireDate: null,
      id: 3,
      jobTitle: 'V.P. General Counsel',
      jobTitleId: 7,
      location: null,
      locationId: 0,
      manager: true,
      managerId: 1,
      personalEmail: null,
      personalPhone: '619-734-9766',
      picture: '',
      status: true,
      userCreated: true,
      userId: 2273,
      userType: 'Admin',
      userTypeId: 1,
      workEmail: 'ally@taylor-corp.net',
      zip: '71000',
      zipId: 413,
      isManager: false,
      employees: []
    },
    {
      address: null,
      alias: 'Jaden Palmer 2',
      birthDate: null,
      city: 'Sarajevo ',
      comment: null,
      country: 'Bosnia and Herzegovina',
      department: 'Brokerage',
      departmentId: 2,
      dialpad: '(619) 719-5650',
      firstName: 'Jasmin',
      lastName: 'Muhotic',
      gender: null,
      hireDate: null,
      id: 4,
      jobTitle: 'Director',
      jobTitleId: 5,
      location: null,
      locationId: 0,
      manager: false,
      managerId: 1,
      personalEmail: null,
      personalPhone: '(619) 719-5650',
      picture: null,
      status: true,
      userCreated: true,
      userId: 2284,
      userType: 'Broker',
      userTypeId: 2,
      workEmail: 'jaden.p@taylor-corp.net',
      zip: '71000',
      zipId: 413,
      isManager: false,
      employees: []
    },
    {
      address: null,
      alias: 'Jaden Palmer',
      birthDate: null,
      city: 'Sarajevo ',
      comment: null,
      country: 'Bosnia and Herzegovina',
      department: 'Brokerage',
      departmentId: 2,
      dialpad: '(619) 719-5650',
      firstName: 'Ana',
      lastName: 'Tomic',
      gender: null,
      hireDate: null,
      id: 5,
      jobTitle: 'Communications Director',
      jobTitleId: 5,
      location: null,
      locationId: 0,
      manager: false,
      managerId: 1,
      personalEmail: null,
      personalPhone: '(619) 719-5650',
      picture: null,
      status: true,
      userCreated: true,
      userId: 2284,
      userType: 'Broker',
      userTypeId: 2,
      workEmail: 'jaden.p@taylor-corp.net',
      zip: '71000',
      zipId: 413,
      isManager: false,
      employees: []
    },
    {
      address: null,
      alias: "Sophia Barron",
      birthDate: null,
      city: "Sarajevo ",
      comment: null,
      country: "Bosnia and Herzegovina",
      department: "Brokerage",
      departmentId: 2,
      dialpad: "(619) 413-0578",
      firstName: "Bryant ",
      lastName: "Wallace",
      gender: null,
      hireDate: null,
      id: 6,
      isManager: false,
      jobTitle: "V.P. Bussiness Development",
      jobTitleId: 5,
      location: null,
      locationId: 0,
      manager: null,
      managerId: 1,
      personalEmail: null,
      personalPhone: "(619) 413-0578",
      picture: null,
      status: true,
      userCreated: true,
      userId: 2282,
      userType: "Broker",
      userTypeId: 2,
      workEmail: "sophia.barron@taylor-corp.net",
      zip: "71000",
      zipId: 413,
      employees: []
    },
    {
      address: null,
      alias: "Sophia Barron 2",
      birthDate: null,
      city: "Sarajevo ",
      comment: null,
      country: "Bosnia and Herzegovina",
      department: "Brokerage",
      departmentId: 2,
      dialpad: "(619) 413-0578",
      firstName: "Dino",
      lastName: "Cehajic",
      gender: null,
      hireDate: null,
      id: 7,
      isManager: false,
      jobTitle: "Director of IT",
      jobTitleId: 5,
      location: null,
      locationId: 0,
      manager: true,
      managerId: 4,
      personalEmail: null,
      personalPhone: "(619) 413-0578",
      picture: null,
      status: true,
      userCreated: true,
      userId: 2282,
      userType: "Broker",
      userTypeId: 2,
      workEmail: "sophia.barron@taylor-corp.net",
      zip: "71000",
      zipId: 413,
      employees: []
    },
    {
      address: null,
      alias: "Sophia Barron 2",
      birthDate: null,
      city: "Sarajevo ",
      comment: null,
      country: "Bosnia and Herzegovina",
      department: "Brokerage",
      departmentId: 2,
      dialpad: "(619) 413-0578",
      firstName: "Erdal",
      lastName: "Balkanli",
      gender: null,
      hireDate: null,
      id: 8,
      isManager: false,
      jobTitle: "IT Technician",
      jobTitleId: 5,
      location: null,
      locationId: 0,
      manager: null,
      managerId: 4,
      personalEmail: null,
      personalPhone: "(619) 413-0578",
      picture: null,
      status: true,
      userCreated: true,
      userId: 2282,
      userType: "Broker",
      userTypeId: 2,
      workEmail: "sophia.barron@taylor-corp.net",
      zip: "71000",
      zipId: 413,
      employees: []
    },
    {
      address: null,
      alias: "Sophia Barron 2",
      birthDate: null,
      city: "Sarajevo ",
      comment: null,
      country: "Bosnia and Herzegovina",
      department: "Brokerage",
      departmentId: 2,
      dialpad: "(619) 413-0578",
      firstName: "Alma",
      lastName: "Hodzic",
      gender: null,
      hireDate: null,
      id: 9,
      isManager: false,
      jobTitle: "HR Director",
      jobTitleId: 5,
      location: null,
      locationId: 0,
      manager: null,
      managerId: 4,
      personalEmail: null,
      personalPhone: "(619) 413-0578",
      picture: null,
      status: true,
      userCreated: true,
      userId: 2282,
      userType: "Broker",
      userTypeId: 2,
      workEmail: "sophia.barron@taylor-corp.net",
      zip: "71000",
      zipId: 413,
      employees: []
    },
    {
      address: null,
      alias: "Sophia Barron 2",
      birthDate: null,
      city: "Sarajevo ",
      comment: null,
      country: "Bosnia and Herzegovina",
      department: "Brokerage",
      departmentId: 2,
      dialpad: "(619) 413-0578",
      firstName: "Jasna",
      lastName: "Korda Korda",
      gender: null,
      hireDate: null,
      id: 10,
      isManager: false,
      jobTitle: "Business Director",
      jobTitleId: 5,
      location: null,
      locationId: 0,
      manager: null,
      managerId: 4,
      personalEmail: null,
      personalPhone: "(619) 413-0578",
      picture: null,
      status: true,
      userCreated: true,
      userId: 2282,
      userType: "Broker",
      userTypeId: 2,
      workEmail: "sophia.barron@taylor-corp.net",
      zip: "71000",
      zipId: 413,
      employees: []
    }

  ];

  listOfEmployees = [];
  ngOnInit(): void {
    this.getMangers();
  }

  getMangers() {
    const idMapping = this.testList.reduce((acc, el, i) => {
      acc[el.id] = i;
      return acc;
    }, {})


    let manager = {};
    this.testList.forEach(el => {
      if (el.managerId === 0) {
        manager = el;
        return manager;
      }
      const managerEl = this.testList[idMapping[el.managerId]];
      managerEl.employees = ([...(managerEl.employees || []), el]);
    });
    this.listOfEmployees.push(manager);

  }
  toggleShow(employee) {
    if (employee) {

      employee.hidden = !employee.hidden;
    }
  }
}
